title: Elixir em Foco
theme: minima

# Como é um Project Page, o baseurl deve ser o nome do repositório
url: "https://elixiremfoco.github.io"
baseurl: "/ecossistema"

# Opções extras
lang: pt-BR
author: Elixir em Foco
github_username: ElixiremFoco
